accessing
error: error
	^ self at: 'Error' put: error